#!/bin/bash
set -e

DOCKER_MACHINE_GITURL=https://raw.githubusercontent.com/docker/machine/master/Dockerfile
DOCKER_FILE_MACHINE="$(git rev-parse --show-toplevel)/.dockerfile.machine"

if [ -z "$1" ]; then
    OS_PLATFORM_ARG=(-os="darwin linux windows")
else
    OS_PLATFORM_ARG=($1)
fi

if [ -z "$2" ]; then
    OS_ARCH_ARG=(-arch="386 amd64 arm")
else
    OS_ARCH_ARG=($2)
fi

# Build Docker image unless we opt out of it
if [[ -z "$SKIP_BUILD" ]]; then
    curl -s $DOCKER_MACHINE_GITURL > $DOCKER_FILE_MACHINE
    docker build -f $DOCKER_FILE_MACHINE -t docker-machine .
fi

# Get rid of existing binaries
rm -f docker-machine*
rm -rf Godeps/_workspace/pkg
if [[ -z "$SKIP_USEDOCKER" ]]; then
    docker run --rm \
    -v `pwd`:/go/src/github.com/HewlettPackard/docker-machine-oneview \
    docker-machine \
    gox "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" -output="docker-machine-driver-oneview_{{.OS}}-{{.Arch}}" -ldflags="-w -X github.com/HewlettPackard/docker-machine-oneview/version.GitCommit `git rev-parse --short HEAD`"
else
    _SAVEGOPATH=$GOPATH
    _PROJECT_ROOT=`git rev-parse --show-toplevel`
    mkdir -p /tmp/go/src/github.com/HewlettPackard
    ln -s $_PROJECT_ROOT /tmp/go/src/github.com/HewlettPackard/docker-machine-oneview
    GOPATH=/tmp/go/src/github.com/HewlettPackard/docker-machine-oneview/Godeps/_workspace:/tmp/go:$GOPATH
    gox "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" -output="docker-machine-driver-oneview_{{.OS}}-{{.Arch}}" -ldflags="-w -X github.com/HewlettPackard/docker-machine-oneview/version.GitCommit `git rev-parse --short HEAD`"
    GOPATH=$_SAVEGOPATH
fi
